# https://taskfile.dev

version: "3"

tasks:
  pre:build:
    silent: true
    cmds:
      - task: pre:build:{{OS}}

  pre:build:windows:
    silent: true
    internal: true
    cmds:
      - pwsh -NoProfile -Command "mkdir bin -Force | Out-Null"

  pre:build:linux:
    silent: true
    internal: true
    cmds:
      - mkdir bin -f

  build:
    generates:
      - bin/krobe{{exeExt}}
    sources:
      - /**/*.c
      - /**/*.cpp
      - /**/*.odin
      - assets/krobe.rc
    cmds:
      - task: build:libs:{{OS}}
      - task: build:odin:{{OS}}

  build:odin:window:
    silent: true
    cmds:
      - odin build . -out:bin/krobe{{exeExt}} -o:speed -resource:assets/krobe.rc

  build:odin:linux:
    silent: true
    cmds:
      - odin build . -out:bin/krobe{{exeExt}} -o:speed

  run:
    cmds:
      - task: build:libs
      - odin run . -resource:assets/krobe.rc
      - task: del:temp:{{OS}}

  del:temp:windows:
    silent: true
    internal: true
    cmds:
      - pwsh -NoProfile -Command "del krobe{{exeExt}}"

  build:libs:windows:
    generates:
      - bin/krobe.lib
    sources:
      - /**/*.c
      - /**/*.cpp
    silent: true
    cmds:
      - task: pre:build
      - pwsh -NoProfile -ExecutionPolicy Bypass -File "./win_vs_build.ps1" -Target all -WorkingDir "{{.USER_WORKING_DIR}}"

  build:libs:linux:
    generates:
      - bin/krobe.a
    sources:
      - /**/*.c
      - /**/*.cpp
    silent: true
    cmds:
      - task: pre:build
      - sh ./linux_gcc_build.sh
