name: Build and Test

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [
            windows-latest,
            ubuntu-latest,
            # macos-latest
          ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ilammy/msvc-dev-cmd@v1
        if: startsWith(matrix.os, 'windows')
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: build
        timeout-minutes: 5
        run: |
          task build:release

      - name: test # run tests only after building since we need the c/c++ libs to link with
        run: |
          odin test . -all-packages

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: |
            ./bin/*
          if-no-files-found: error
